"""belohnungen

Revision ID: 9569a4c5a2eb
Revises: 537a8a614cf9
Create Date: 2026-09-25 12:05:34.845193
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

OLD_SOURCE_CHECK = (
    "(kind NOT IN ('task_completed', 'task_undone') OR task_date IS NOT NULL)"
    " AND (kind <> 'manual' OR reason IS NOT NULL)"
)
NEW_SOURCE_CHECK = (
    OLD_SOURCE_CHECK + " AND (kind <> 'reward_redeemed' OR redemption_id IS NOT NULL)"
)

revision: str = "9569a4c5a2eb"
down_revision: str | Sequence[str] | None = "537a8a614cf9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rewards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("icon", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("cost", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("cost > 0", name=op.f("ck_rewards_cost_positive")),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["family_members.id"],
            name=op.f("fk_rewards_member_id_family_members"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rewards")),
    )
    op.create_index(op.f("ix_rewards_member_id"), "rewards", ["member_id"], unique=False)
    op.create_table(
        "reward_redemptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reward_id", sa.Integer(), nullable=True),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("reward_name", sa.String(length=100), nullable=False),
        sa.Column("reward_icon", sa.String(length=100), nullable=False),
        sa.Column("cost", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["family_members.id"],
            name=op.f("fk_reward_redemptions_member_id_family_members"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reward_id"],
            ["rewards.id"],
            name=op.f("fk_reward_redemptions_reward_id_rewards"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reward_redemptions")),
    )
    op.create_index(
        op.f("ix_reward_redemptions_member_id"), "reward_redemptions", ["member_id"], unique=False
    )
    op.add_column("point_transactions", sa.Column("redemption_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("fk_point_transactions_redemption_id_reward_redemptions"),
        "point_transactions",
        "reward_redemptions",
        ["redemption_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
    # Von Hand: Einlösungs-Buchungen brauchen ihre Einlösung als Quelle.
    op.drop_constraint(
        op.f("ck_point_transactions_source_for_kind"), "point_transactions", type_="check"
    )
    op.create_check_constraint(
        op.f("ck_point_transactions_source_for_kind"), "point_transactions", NEW_SOURCE_CHECK
    )


def downgrade() -> None:
    op.execute("DELETE FROM point_transactions WHERE kind = 'reward_redeemed'")
    op.drop_constraint(
        op.f("ck_point_transactions_source_for_kind"), "point_transactions", type_="check"
    )
    op.create_check_constraint(
        op.f("ck_point_transactions_source_for_kind"), "point_transactions", OLD_SOURCE_CHECK
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_point_transactions_redemption_id_reward_redemptions"),
        "point_transactions",
        type_="foreignkey",
    )
    op.drop_column("point_transactions", "redemption_id")
    op.drop_index(op.f("ix_reward_redemptions_member_id"), table_name="reward_redemptions")
    op.drop_table("reward_redemptions")
    op.drop_index(op.f("ix_rewards_member_id"), table_name="rewards")
    op.drop_table("rewards")
    # ### end Alembic commands ###
