"""punktebuchungen

Revision ID: 537a8a614cf9
Revises: 23041299214b
Create Date: 2026-09-25 11:21:56.841549
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "537a8a614cf9"
down_revision: str | Sequence[str] | None = "23041299214b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "point_transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.String(length=200), nullable=True),
        sa.Column("task_id", sa.Integer(), nullable=True),
        sa.Column("task_date", sa.Date(), nullable=True),
        sa.Column("created_by_user_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(kind NOT IN ('task_completed', 'task_undone') OR task_date IS NOT NULL)"
            " AND (kind <> 'manual' OR reason IS NOT NULL)",
            name=op.f("ck_point_transactions_source_for_kind"),
        ),
        sa.CheckConstraint("amount <> 0", name=op.f("ck_point_transactions_amount_not_zero")),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_point_transactions_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["family_members.id"],
            name=op.f("fk_point_transactions_member_id_family_members"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
            name=op.f("fk_point_transactions_task_id_tasks"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_point_transactions")),
    )
    op.create_index(
        op.f("ix_point_transactions_member_id"), "point_transactions", ["member_id"], unique=False
    )
    # Bisherige Erledigungen haben keine Buchung; Rückgängig bucht bei ihnen daher nichts zurück.
    op.add_column(
        "task_completions", sa.Column("points", sa.Integer(), server_default="0", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task_completions", "points")
    op.drop_index(op.f("ix_point_transactions_member_id"), table_name="point_transactions")
    op.drop_table("point_transactions")
    # ### end Alembic commands ###
