"""erledigungen

Revision ID: 23041299214b
Revises: 606c78dd686a
Create Date: 2026-09-25 10:55:08.430056
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "23041299214b"
down_revision: str | Sequence[str] | None = "606c78dd686a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_completions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["family_members.id"],
            name=op.f("fk_task_completions_member_id_family_members"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
            name=op.f("fk_task_completions_task_id_tasks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_completions")),
        sa.UniqueConstraint(
            "task_id", "member_id", "date", name=op.f("uq_task_completions_task_id")
        ),
    )
    op.create_index(op.f("ix_task_completions_date"), "task_completions", ["date"], unique=False)
    op.create_index(
        op.f("ix_task_completions_member_id"), "task_completions", ["member_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_task_completions_member_id"), table_name="task_completions")
    op.drop_index(op.f("ix_task_completions_date"), table_name="task_completions")
    op.drop_table("task_completions")
    # ### end Alembic commands ###
