"""elternkontrolle

Revision ID: bbaf01876606
Revises: 9569a4c5a2eb
Create Date: 2026-09-25 12:24:17.106374
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "bbaf01876606"
down_revision: str | Sequence[str] | None = "9569a4c5a2eb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task_completions", sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("task_completions", sa.Column("approved_by_user_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("fk_task_completions_approved_by_user_id_users"),
        "task_completions",
        "users",
        ["approved_by_user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "tasks", sa.Column("needs_approval", sa.Boolean(), server_default="false", nullable=False)
    )
    # ### end Alembic commands ###
    # Bisherige Erledigungen gelten als geprüft (ihre Punkte sind schon gebucht).
    op.execute("UPDATE task_completions SET approved_at = completed_at")


def downgrade() -> None:
    # Ungeprüfte Erledigungen haben keine Buchung; ohne Kontrolle würde Rückgängig sonst
    # Punkte abziehen, die nie gutgeschrieben wurden.
    op.execute("DELETE FROM task_completions WHERE approved_at IS NULL")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "needs_approval")
    op.drop_constraint(
        op.f("fk_task_completions_approved_by_user_id_users"),
        "task_completions",
        type_="foreignkey",
    )
    op.drop_column("task_completions", "approved_by_user_id")
    op.drop_column("task_completions", "approved_at")
    # ### end Alembic commands ###
