"""flexible aufgaben

Revision ID: 39fd6b074dbb
Revises: bbaf01876606
Create Date: 2026-09-25 12:54:45.508345
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

OLD_CHECK = (
    "(kind <> 'weekly' OR cardinality(weekdays) > 0) AND (kind <> 'once' OR date IS NOT NULL)"
)
NEW_CHECK = OLD_CHECK + " AND (kind <> 'flexible' OR (date IS NOT NULL AND interval_days > 0))"

revision: str = "39fd6b074dbb"
down_revision: str | Sequence[str] | None = "bbaf01876606"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task_recurrences", sa.Column("interval_days", sa.SmallInteger(), nullable=True))
    op.add_column(
        "tasks", sa.Column("shared", sa.Boolean(), server_default="false", nullable=False)
    )
    # ### end Alembic commands ###
    # Von Hand: flexible Wiederholungen brauchen Startdatum und Intervall.
    op.drop_constraint(
        op.f("ck_task_recurrences_fields_for_kind"), "task_recurrences", type_="check"
    )
    op.create_check_constraint(
        op.f("ck_task_recurrences_fields_for_kind"), "task_recurrences", NEW_CHECK
    )


def downgrade() -> None:
    # Flexible Aufgaben gibt es danach nicht mehr; sie werden zu täglichen.
    op.execute("UPDATE task_recurrences SET kind = 'daily', date = NULL WHERE kind = 'flexible'")
    op.drop_constraint(
        op.f("ck_task_recurrences_fields_for_kind"), "task_recurrences", type_="check"
    )
    op.create_check_constraint(
        op.f("ck_task_recurrences_fields_for_kind"), "task_recurrences", OLD_CHECK
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "shared")
    op.drop_column("task_recurrences", "interval_days")
    # ### end Alembic commands ###
