"""routinen und extras

Revision ID: c7d8ccb2944c
Revises: 2c7d8630bc70
Create Date: 2026-09-25 20:24:30.531570
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c7d8ccb2944c"
down_revision: str | Sequence[str] | None = "2c7d8630bc70"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task_assignments", sa.Column("position", sa.Integer(), server_default="0", nullable=False)
    )
    op.add_column("tasks", sa.Column("extra", sa.Boolean(), server_default="false", nullable=False))
    # ### end Alembic commands ###
    # Startreihenfolge je Person: nach Tagesabschnitt, dann wie bisher nach Anlage.
    op.execute(
        """
        UPDATE task_assignments AS a SET position = ranked.position
        FROM (
            SELECT a2.id, row_number() OVER (
                PARTITION BY a2.member_id
                ORDER BY CASE t.time_of_day
                    WHEN 'morning' THEN 0 WHEN 'midday' THEN 1
                    WHEN 'afternoon' THEN 2 WHEN 'evening' THEN 3 ELSE 4 END,
                    t.id
            ) - 1 AS position
            FROM task_assignments a2 JOIN tasks t ON t.id = a2.task_id
        ) AS ranked
        WHERE a.id = ranked.id
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "extra")
    op.drop_column("task_assignments", "position")
    # ### end Alembic commands ###
