"""familienmitglieder

Revision ID: 50f414301965
Revises: ef3746eeb05a
Create Date: 2026-09-25 08:48:25.288738
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "50f414301965"
down_revision: str | Sequence[str] | None = "ef3746eeb05a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "family_members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("color", sa.String(length=20), nullable=False),
        sa.Column("avatar", sa.String(length=64), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_family_members_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_family_members")),
        sa.UniqueConstraint("color", name=op.f("uq_family_members_color")),
        sa.UniqueConstraint("user_id", name=op.f("uq_family_members_user_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("family_members")
    # ### end Alembic commands ###
