"""aufgaben und wiederholungen

Revision ID: 606c78dd686a
Revises: 50f414301965
Create Date: 2026-09-25 09:22:24.710190
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "606c78dd686a"
down_revision: str | Sequence[str] | None = "50f414301965"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("icon", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("time_of_day", sa.String(length=20), nullable=True),
        sa.Column("color", sa.String(length=20), nullable=True),
        sa.Column("active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("points >= 0", name=op.f("ck_tasks_points_not_negative")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
    )
    op.create_table(
        "task_recurrences",
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("weekdays", postgresql.ARRAY(sa.SmallInteger()), nullable=True),
        sa.Column("date", sa.Date(), nullable=True),
        sa.CheckConstraint(
            "(kind <> 'weekly' OR cardinality(weekdays) > 0)"
            " AND (kind <> 'once' OR date IS NOT NULL)",
            name=op.f("ck_task_recurrences_fields_for_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
            name=op.f("fk_task_recurrences_task_id_tasks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("task_id", name=op.f("pk_task_recurrences")),
    )
    op.create_table(
        "task_assignments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["family_members.id"],
            name=op.f("fk_task_assignments_member_id_family_members"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
            name=op.f("fk_task_assignments_task_id_tasks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_assignments")),
        sa.UniqueConstraint("task_id", "member_id", name=op.f("uq_task_assignments_task_id")),
    )
    op.create_index(
        op.f("ix_task_assignments_member_id"), "task_assignments", ["member_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_task_assignments_member_id"), table_name="task_assignments")
    op.drop_table("task_assignments")
    op.drop_table("task_recurrences")
    op.drop_table("tasks")
    # ### end Alembic commands ###
