"""wetter

Revision ID: 2c7d8630bc70
Revises: db3210c96f59
Create Date: 2026-09-25 18:18:04.598304
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "2c7d8630bc70"
down_revision: str | Sequence[str] | None = "db3210c96f59"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("families", sa.Column("weather_place", sa.String(length=200), nullable=True))
    op.add_column("families", sa.Column("weather_latitude", sa.Float(), nullable=True))
    op.add_column("families", sa.Column("weather_longitude", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("families", "weather_longitude")
    op.drop_column("families", "weather_latitude")
    op.drop_column("families", "weather_place")
    # ### end Alembic commands ###
