"""kalender und termine

Revision ID: 8ef55057bafc
Revises: 4b0fab2fbad9
Create Date: 2026-09-25 16:49:03.405873
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "8ef55057bafc"
down_revision: str | Sequence[str] | None = "4b0fab2fbad9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calendars",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("connection_id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(length=1024), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("primary", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("selected", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=True),
        sa.Column("sync_token", sa.Text(), nullable=True),
        sa.Column("window_start", sa.Date(), nullable=True),
        sa.Column("window_loaded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sync_error", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["calendar_connections.id"],
            name=op.f("fk_calendars_connection_id_calendar_connections"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["family_members.id"],
            name=op.f("fk_calendars_member_id_family_members"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calendars")),
        sa.UniqueConstraint(
            "connection_id", "external_id", name=op.f("uq_calendars_connection_id")
        ),
    )
    op.create_index(op.f("ix_calendars_member_id"), "calendars", ["member_id"], unique=False)
    op.create_table(
        "calendar_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("calendar_id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(length=1024), nullable=False),
        sa.Column("ical_uid", sa.String(length=1024), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("all_day", sa.Boolean(), nullable=False),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.CheckConstraint(
            "(all_day AND start_date IS NOT NULL AND end_date IS NOT NULL)"
            " OR (NOT all_day AND start_at IS NOT NULL AND end_at IS NOT NULL)",
            name=op.f("ck_calendar_events_times_for_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["calendar_id"],
            ["calendars.id"],
            name=op.f("fk_calendar_events_calendar_id_calendars"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calendar_events")),
        sa.UniqueConstraint(
            "calendar_id", "external_id", name=op.f("uq_calendar_events_calendar_id")
        ),
    )
    op.create_index(
        op.f("ix_calendar_events_start_at"), "calendar_events", ["start_at"], unique=False
    )
    op.add_column(
        "families",
        sa.Column("calendar_color", sa.String(length=20), server_default="pink", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("families", "calendar_color")
    op.drop_index(op.f("ix_calendar_events_start_at"), table_name="calendar_events")
    op.drop_table("calendar_events")
    op.drop_index(op.f("ix_calendars_member_id"), table_name="calendars")
    op.drop_table("calendars")
    # ### end Alembic commands ###
