"""Routinen als eigene Blöcke

Übernimmt bestehende Routinen: Je Kind und Tagesabschnitt werden die täglichen und wochentäglichen
Aufgaben zu Routinen; Wochentage mit denselben Schritten bilden eine Variante.

Revision ID: 075cb1d2b6c3
Revises: 5ec074ee95f5
Create Date: 2026-09-28 12:41:14.143910
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "075cb1d2b6c3"
down_revision: str | Sequence[str] | None = "5ec074ee95f5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "routines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("time_of_day", sa.String(length=20), nullable=False),
        sa.Column(
            "weekdays", postgresql.ARRAY(sa.SmallInteger()), server_default="{}", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["family_members.id"],
            name=op.f("fk_routines_member_id_family_members"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_routines")),
    )
    op.create_index(op.f("ix_routines_member_id"), "routines", ["member_id"], unique=False)
    op.create_table(
        "routine_steps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("routine_id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), server_default="0", nullable=False),
        sa.Column("optional", sa.Boolean(), server_default="false", nullable=False),
        sa.ForeignKeyConstraint(
            ["routine_id"],
            ["routines.id"],
            name=op.f("fk_routine_steps_routine_id_routines"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
            name=op.f("fk_routine_steps_task_id_tasks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_routine_steps")),
        sa.UniqueConstraint("routine_id", "task_id", name=op.f("uq_routine_steps_routine_id")),
    )
    op.create_index(op.f("ix_routine_steps_task_id"), "routine_steps", ["task_id"], unique=False)
    # ### end Alembic commands ###
    _take_over_routines()


def _take_over_routines() -> None:
    bind = op.get_bind()
    rows = bind.execute(
        sa.text(
            """
            SELECT a.member_id, t.time_of_day, t.id, r.kind, r.weekdays
            FROM tasks t
            JOIN task_assignments a ON a.task_id = t.id
            JOIN task_recurrences r ON r.task_id = t.id
            JOIN family_members m ON m.id = a.member_id
            WHERE m.role = 'child' AND NOT t.extra AND t.time_of_day IS NOT NULL
              AND r.kind IN ('daily', 'weekly')
            ORDER BY a.member_id, t.time_of_day, a.position, t.id
            """
        )
    ).all()
    # (Kind, Tagesabschnitt) → Aufgaben in Reihenfolge, je mit ihren Wochentagen.
    groups: dict[tuple[int, str], list[tuple[int, set[int]]]] = {}
    for member_id, time_of_day, task_id, kind, weekdays in rows:
        days = set(range(1, 8)) if kind == "daily" else set(weekdays or ())
        groups.setdefault((member_id, time_of_day), []).append((task_id, days))

    for (member_id, time_of_day), tasks in groups.items():
        # Wochentage mit genau denselben Schritten werden eine Variante.
        variants: dict[tuple[int, ...], list[int]] = {}
        for day in range(1, 8):
            steps = tuple(task_id for task_id, days in tasks if day in days)
            if steps:
                variants.setdefault(steps, []).append(day)
        for steps, days in variants.items():
            routine_id = bind.execute(
                sa.text(
                    "INSERT INTO routines (member_id, time_of_day, weekdays)"
                    " VALUES (:member_id, :time_of_day, :weekdays) RETURNING id"
                ),
                {"member_id": member_id, "time_of_day": time_of_day, "weekdays": days},
            ).scalar_one()
            for position, task_id in enumerate(steps):
                bind.execute(
                    sa.text(
                        "INSERT INTO routine_steps (routine_id, task_id, position)"
                        " VALUES (:routine_id, :task_id, :position)"
                    ),
                    {"routine_id": routine_id, "task_id": task_id, "position": position},
                )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_routine_steps_task_id"), table_name="routine_steps")
    op.drop_table("routine_steps")
    op.drop_index(op.f("ix_routines_member_id"), table_name="routines")
    op.drop_table("routines")
    # ### end Alembic commands ###
