"""reihenfolge der personen

Revision ID: 732d75c2b37a
Revises: 39fd6b074dbb
Create Date: 2026-09-25 14:39:13.963618
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "732d75c2b37a"
down_revision: str | Sequence[str] | None = "39fd6b074dbb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "family_members", sa.Column("position", sa.Integer(), server_default="0", nullable=False)
    )
    # ### end Alembic commands ###
    # Bisherige Reihenfolge: nach Anlegen.
    op.execute("UPDATE family_members SET position = id")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("family_members", "position")
    # ### end Alembic commands ###
