"""feiertage ferien und termindetails

Revision ID: db3210c96f59
Revises: 8ef55057bafc
Create Date: 2026-09-25 17:41:46.498139
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "db3210c96f59"
down_revision: str | Sequence[str] | None = "8ef55057bafc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "school_holidays",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("region", sa.String(length=10), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("name_de", sa.String(length=200), nullable=False),
        sa.Column("name_en", sa.String(length=200), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_school_holidays")),
    )
    op.create_index(op.f("ix_school_holidays_region"), "school_holidays", ["region"], unique=False)
    op.add_column("calendar_events", sa.Column("location", sa.String(length=500), nullable=True))
    op.add_column("calendar_events", sa.Column("description", sa.Text(), nullable=True))
    op.add_column("families", sa.Column("holiday_region", sa.String(length=10), nullable=True))
    op.add_column(
        "families",
        sa.Column("show_public_holidays", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "families",
        sa.Column("show_school_holidays", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###
    # Bereits geladene Termine haben noch keinen Ort und keine Beschreibung: beim nächsten
    # Durchlauf neu laden.
    op.execute("UPDATE calendars SET window_loaded_at = NULL")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("families", "show_school_holidays")
    op.drop_column("families", "show_public_holidays")
    op.drop_column("families", "holiday_region")
    op.drop_column("calendar_events", "description")
    op.drop_column("calendar_events", "location")
    op.drop_index(op.f("ix_school_holidays_region"), table_name="school_holidays")
    op.drop_table("school_holidays")
    # ### end Alembic commands ###
